import gradio as gr
import shutil
import os
from typing import List, Tuple
from ingest import trigger_ingestion
from typing import Any
from PIL import Image
from io import BytesIO
import base64
from langchain_classic.retrievers.multi_vector import MultiVectorRetriever
from retrieval import multimodal_rag

DOCUMENT_DIR = "./documents"

if os.path.exists(DOCUMENT_DIR):
    shutil.rmtree(DOCUMENT_DIR)

os.makedirs(DOCUMENT_DIR, exist_ok=True)

def save_file(file_obj: Any, retriever: MultiVectorRetriever) -> Tuple[str, MultiVectorRetriever]:
    """
    The method takes a file object and a retriever as input, saves the file to a specified directory,
    and triggers the ingestion process to prepare the retriever for querying.

    Parameters
    ----------
    file_obj (Any): The file object representing the uploaded file.
    retriever (MultiVectorRetriever): The multi-vector retriever to be updated after ingestion.

    Returns
    -------
    tuple[str, MultiVectorRetriever]: A tuple containing a status message and the updated multi-vector retriever after ingestion. 
    """
    if not os.path.exists(DOCUMENT_DIR):
        os.makedirs(DOCUMENT_DIR)

    file_name = os.path.basename(file_obj.name)
    destination_path = os.path.join(DOCUMENT_DIR, file_name)

    if os.path.exists(destination_path):
        return f"File already exists: {file_name}. Upload skipped."

    shutil.copy(file_obj.name, destination_path)
    # Upload, ingest and get the retriever ready for querying
    retriever = trigger_ingestion(destination_path)
    return f"Ingestion completed successfully: {file_name}", retriever

def decode_base64_image(img_str: str) -> Image.Image:
    """
    The method takes a base64 encoded image string as input, 
    decodes it, and returns a PIL Image object.

    Parameters
    ----------
    img_str (str): A base64 encoded string representation of the image.

    Returns
    -------
    Image.Image: A PIL Image object.
    """
    if "," in img_str:
        img_str = img_str.split(",")[1]

    img_data = base64.b64decode(img_str)
    return Image.open(BytesIO(img_data))

def return_results(query: str, retriever: MultiVectorRetriever) -> Tuple[str, List[Image.Image]]:
    """
    The method takes a user query and a retriever as input and returns 
    the answer generated by the multimodal RAG system.

    Parameters
    ----------
    query (str): The user query for which the answer needs to be generated.
    retriever (MultiVectorRetriever): The multi-vector retriever to use for retrieving the relevant context.

    Returns
    -------
    str: The answer generated by the multimodal RAG system based on the user query and the retrieved context.
    List[Image.Image]: A list of PIL Image objects that are part of the retrieved context for the user query.
    """
    if retriever is None:
        return "Please upload a document first."
    
    result = multimodal_rag(query, retriever)
    answer = result.get("answer", "")
    images_b64 = result.get("context", {}).get("images", [])
    images = [decode_base64_image(img) for img in images_b64]
    return answer, images

with gr.Blocks(title="RAG Based Document Question Answering System") as demo:
    gr.Markdown("# RAG Based Document Question Answering System")

    gr.Markdown("## Upload and Ingest Document")

    file_input = gr.File(label="Upload your file", file_count="single")
    upload_btn = gr.Button("Run Ingestion")

    status = gr.Textbox(label="Status", interactive=False)

    gr.Markdown("## Ask a Question")
    query_input = gr.Textbox(label="Your Query")
    query_btn = gr.Button("Submit Query")

    chatbot = gr.Markdown(label="Answer")  # supports rich text
    gallery = gr.Gallery(label="Images", columns=3)

    retriever_state = gr.State(None)
    upload_btn.click(
        fn=save_file,
        inputs=[file_input, retriever_state],
        outputs=[status, retriever_state]
    )

    query_btn.click(
        fn=return_results,
        inputs=[query_input, retriever_state],
        outputs=[chatbot, gallery]
    )

if __name__ == "__main__":
    demo.launch(theme=gr.themes.Soft())