"""
The module contains code for preprocessing and ingesting documents to multi-vector retrieval store.
"""
import logging
import shutil
from typing import List, Tuple
logging.basicConfig(level=logging.INFO)
import os
from langchain_google_genai import ChatGoogleGenerativeAI
import base64
from langchain_community.document_loaders import UnstructuredPDFLoader
import htmltabletomd
from langchain_core.messages import HumanMessage
import uuid
from langchain_chroma import Chroma
from langchain_classic.schema.document import Document
from langchain_classic.storage import InMemoryStore
from langchain_classic.schema.document import Document
from langchain_classic.retrievers.multi_vector import MultiVectorRetriever
from langchain_google_genai import GoogleGenerativeAIEmbeddings

# Get the Gemini API key from the environment variable
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# Default Embedding model
DEFAULT_EMBEDDING_MODEL = "gemini-embedding-001"

# Initialize the Gemini model for Table and Image Summarization.
summarizer_model = ChatGoogleGenerativeAI(
    model="gemini-2.5-pro",
    temperature=0,
    max_retries=2
)
# Default Images Directory
IMAGES_DIR = "./figures"

if os.path.exists(IMAGES_DIR):
    shutil.rmtree(IMAGES_DIR)

def separate_text_and_tables(data: List[Document]
                             ) -> Tuple[List[str], List[str]]:
    """
    The method takes a list of elements (documents) and separates the text content and tables. 
    
    Parameters:
    -----------
    data (List[str]): A list of documents, where each document may contain text content and/or tables in HTML format.

    Returns:
    --------
    tuple: A tuple containing two lists: one containing the text content and the other containing the tables in markdown format.
    """
    docs = []
    tables = []
    for doc in data:
        html_table = doc.metadata.get("text_as_html")

        if html_table:
            md_table = htmltabletomd.convert_table(html_table)
            tables.append(md_table)

        if doc.page_content:
            docs.append(doc.page_content)

    return docs, tables

def build_prompt(element: str) -> str:
    """
    The method builds a prompt for summarizing the given 
    element (text or table).

    Parameters:
    -----------
    element (str): The text content or table in markdown format that needs to be summarized.

    Returns
    -------
    str: A prompt string that can be used to generate a summary of the given element using the Gemini model.
    """
    return f"""
    You are an assistant tasked with summarizing tables and text.

    Give a concise summary of the content.

    Respond ONLY with the summary.

    Content:
    {element}
    """

def summarize(element: str) -> str:
    """
    Summarizes the given element (text or table) 
    using the Gemini model and returns the summary.

    Parameters
    ----------
    element (str): The text content or table in markdown format that needs to be summarized.

    Returns
    -------
    str: A summary of the given element generated by the Gemini model.
    """
    prompt = build_prompt(element)
    response = summarizer_model.invoke(prompt)
    return response.content

def return_summaries(docs: List[str], 
                     tables: List[str]) -> Tuple[List[str], List[str]]:
    """
    The method takes list of text documents and tables in markdown format as input
    and returns their summaries as output.

    Parameters
    ----------
    docs (List[str]): A list of text documents that need to be summarized.
    tables (List[str]): A list of tables in markdown format that need to be summarized.

    Returns
    -------
    Tuple[List[str], List[str]]: A tuple containing two lists: one with the summaries of the text documents 
        and the other with the summaries of the tables.
    """
    text_summaries = []
    table_summaries = []

    for doc in docs:
        text_summaries.append(summarize(doc))

    for table in tables:
        table_summaries.append(summarize(table))
    
    return text_summaries, table_summaries

def encode_image(image_path: str) -> str:
    """
    Encodes the image as base64 string and returns it.

    Parameters
    ----------
    image_path (str): The file path of the image that needs to be encoded.

    Returns
    -------
    str: A base64 encoded string representation of the image.
    """
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

def summarize_image(img_base64: str, prompt: str) -> str:
    """
    Summarizes the image using the Gemini model and returns the summary.

    Parameters
    ----------
    img_base64 (str): A base64 encoded string representation of the image that needs to be summarized.
    prompt (str): A prompt string that can be used to generate a summary of the given image using the Gemini model.

    Returns
    -------
    str: A summary of the given image generated by the Gemini model.
    """
    msg = summarizer_model.invoke(
        [
            HumanMessage(
                content=[
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {"url": 
                                     f"data:image/jpeg;base64,{img_base64}"},
                    },
                ]
            )
        ]
    )
    return msg.content


def generate_img_summaries(path: str) -> Tuple[List[str], List[str]]:
    """
    The method takes the path of the directory containing images as input,
    encodes them as base64 strings, and generates summaries for each image.

    Parameters
    ----------
    path (str): The file path of the directory containing the images that need to be summarized.

    Returns
    -------
    Tuple[List[str], List[str]]: A tuple containing two lists: one with the base64 encoded strings of the 
        images and the other with their summaries.
    """
    # Store image summaries
    image_summaries = []
    images_base64 = []
    
    # Prompt
    prompt = """You are an assistant responsible for generating descriptive summaries of images for retrieval purposes. 
              Keep in mind that images may include elements such as graphs, charts, or tables. 
              These descriptions will be converted into embeddings and used to locate the original image 
              for question answering tasks. Provide a detailed, information-rich description that is optimized 
              for accurate retrieval. Avoid adding extra labels like “Summary:” and rewrite the 
              wording with slight variation.
             """
    
    for img_file in sorted(os.listdir(path)):
        if img_file.endswith(".jpg"):
            img_path = os.path.join(path, img_file)
            base64_image = encode_image(img_path)
            image_summaries.append(summarize_image(base64_image, prompt))
            images_base64.append(base64_image)
    return images_base64, image_summaries

def create_multi_vector_retriever(text_summaries: List[str], 
                                  texts: List[str], 
                                  table_summaries: List[str], 
                                  tables: List[str], 
                                  image_summaries: List[str], 
                                  images: List[str]) -> MultiVectorRetriever:
    """
    The method creates a multi-vector retriever by adding the summaries of text, tables, and 
    images to the vectorstore and their corresponding contents to 
    the docstore.

    Parameters:
    -----------
    text_summaries List(str): List of summaries for text documents.
    texts List(str): List of original text documents.
    table_summaries List(str): List of summaries for tables.
    tables List(str): List of original table documents.
    image_summaries List(str): List of summaries for images.
    images List(str): List of base64 encoded images.

    Returns
    -------
    MultiVectorRetriever: A multi-vector retriever containing the summaries and 
        original contents of text, tables, and images.
    """
    id_key = "doc_id"
    # Initialize the vectorstore and docstore
    vectorstore = Chroma(collection_name="document_qa_rag", 
                       embedding_function=GoogleGenerativeAIEmbeddings(
                           model=DEFAULT_EMBEDDING_MODEL))
    # Initialize the inmemory docstore
    docstore = InMemoryStore()

    # Create the multi-vector retriever
    retriever = MultiVectorRetriever(
        vectorstore=vectorstore,
        docstore=docstore,
        id_key=id_key,
    )
    
    # Helper function to add documents to the vectorstore and docstore
    def add_documents(retriever, doc_summaries, doc_contents):
        doc_ids = [str(uuid.uuid4()) for _ in doc_contents]
        summary_docs = [
            Document(page_content=s, metadata={id_key: doc_ids[i]})
            for i, s in enumerate(doc_summaries)
        ]
        retriever.vectorstore.add_documents(summary_docs)
        retriever.docstore.mset(list(zip(doc_ids, doc_contents)))
        
    if text_summaries:
        add_documents(retriever, text_summaries, texts)
    
    if table_summaries:
        add_documents(retriever, table_summaries, tables)
    
    if image_summaries:
        add_documents(retriever, image_summaries, images)

    return retriever

def trigger_ingestion(file_path: str) -> MultiVectorRetriever:
    """
    The method takes the file path of the PDF document as input, extracts the text, tables, and images,
    generates summaries for each of them, and creates a multi-vector retriever.

    Parameters:
    -----------
    file_path (str): The file path of the PDF document to be ingested.

    Returns:
    --------
    MultiVectorRetriever: A multi-vector retriever containing the summaries and original contents of text, tables, and images.
    """
    # Parse the PDF document and extract text, tables, and images.
    loader = UnstructuredPDFLoader(file_path=file_path, 
                                strategy='hi_res', 
                                extract_images_in_pdf=True, 
                                infer_table_structure=True, 
                                chunking_strategy="by_title", 
                                max_characters=10000,  
                                new_after_n_chars=6000, 
                                combine_text_under_n_chars=2000, 
                                mode='elements', 
                                image_output_dir_path=IMAGES_DIR)
    data = loader.load()

    logging.info(f"Extracted {len(data)} elements from the document.")
    docs, tables = separate_text_and_tables(data)
    logging.info(f"Separated {len(docs)} text documents and {len(tables)} table documents.")

    # Generate summaries for text and tables.
    text_summaries, table_summaries = return_summaries(docs, tables)
    logging.info(f"Generated summaries for text and tables.")

    # Generate summaries for images.
    images_base64, image_summaries = generate_img_summaries(IMAGES_DIR)
    logging.info(f"Generated summaries for images.")

    # Create the multi-vector retriever.
    retriever = create_multi_vector_retriever(
        text_summaries, docs, table_summaries, tables, 
        image_summaries, images_base64)
    logging.info(f"Created multi-vector retriever.")

    return retriever
