"""
The module contains code for retrieving relevant chunks from the multi-vector retriever based on the user queries.
"""
from typing import Dict, List
import logging
logging.basicConfig(level=logging.INFO)
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage
from langchain_classic.retrievers.multi_vector import MultiVectorRetriever

# Initialize the Gemini model for generation.
generation_model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0, max_retries=2)

def split_image_text_types(docs: List[str]) -> Dict:
    """
    The method takes a list of documents and separates the text content 
    and images based on the content type.

    Parameters
    ----------
    docs (List[str]): A list of documents that may contain both text and images in base64 format.

    Returns
    -------
    Dict: A dictionary containing two keys: "images" with a list of base64 encoded images and "texts" with a list of text content.
    """
    images = []
    texts = []

    for doc in docs:
        content = doc.page_content if hasattr(doc, "page_content") else doc
        if isinstance(content, bytes):
            content = content.decode("utf-8")

        if isinstance(content, str) and content.startswith("/9j"):
            images.append(content)
        else:
            texts.append(content)

    return {"images": images, "texts": texts}

def retrieve_context(query: str, 
                     retriever:  MultiVectorRetriever) -> Dict:
    """
    The method takes a user query and a multi-vector retriever as input,
    retrieves the relevant context from the retriever based on the query,
    and separates the text content and images from the retrieved context.

    Parameters
    ----------
    query (str): The user query for which the relevant context needs to be retrieved.
    retriever (MultiVectorRetriever): The multi-vector retriever to use for retrieving the relevant context.

    Returns
    -------
    Dict: A dictionary containing two keys: "images" with a list of base64 
        encoded images and "texts" with a list of text content retrieved from the 
        retriever based on the user query.
    """
    docs = retriever.invoke(query)
    return split_image_text_types(docs)

def build_multimodal_prompt(question: str, context: Dict) -> HumanMessage:
    """
    The method builds a multimodal prompt by combining the question and the retrieved context, 
    which includes both text and images.

    Parameters
    ----------
    question (str): The user query for which the answer needs to be generated. 
    context (Dict): A dictionary containing the retrieved context, which includes both text and images.

    Returns
    -------
    HumanMessage: A HumanMessage object containing the combined prompt with the question and the retrieved context.
    """
    text_context = "\n".join(context["texts"])

    content = []
    content.append({
        "type": "text",
        "text": f"""
        You are an expert analyst.

        Question:
        {question}

        Context:
        {text_context}

        Answer the question using only the provided context.
        Do not hallucinate.
        """
    })

    for img in context["images"]:
        content.append({
            "type": "image_url",
            "image_url": {
                "url": f"data:image/jpeg;base64,{img}"
            }
        })

    return HumanMessage(content=content)

def generate_answer(question: str, context: Dict) -> str:
    """
    The method generates an answer to the user query 
    based on the retrieved context using the Gemini model.

    Parameters
    ----------
    question (str): The user query for which the answer needs to be generated.
    context (Dict): A dictionary containing the retrieved context, which includes both text and images.

    Returns
    -------
    str: An answer to the user query generated by the Gemini model based on the retrieved context.
    """
    prompt = build_multimodal_prompt(question, context)

    response = generation_model.invoke([prompt])

    return response.content

def multimodal_rag(query: str, 
                   retriever: MultiVectorRetriever) -> Dict:
    """
    The method takes a user query as input, 
    retrieves the relevant context using the multi-vector retriever,
    and generates a multimodal response using the Gemini model.

    Parameters
    ----------
    query (str): The user query for which the answer needs to be generated.
    retriever (MultiVectorRetriever): The multi-vector retriever to use for retrieving the relevant context.

    Returns
    -------
    Dict: A dictionary containing the user query, the retrieved context, and the generated answer.
    """
    logging.info(f"Processing query: {query}")
    context = retrieve_context(query, retriever)
    answer = generate_answer(query, context)

    return {
        "input": query,
        "context": context,
        "answer": answer
    }
